export interface BuilderCodeParserOptions {
  suffixMarker?: string;
  maxBuilderCodeBytes?: number;
  builderCodePattern?: RegExp;
}

export interface BuilderCodeParseResult {
  found: boolean;
  builderCode?: string;
  rawSuffix?: string;
  reason?: string;
}

// Builder Codes currently use an ERC-8021-style calldata suffix attribution
// scheme: transaction calldata is followed by structured attribution bytes.
// Smart contracts are expected to ignore the suffix during normal execution,
// while offchain indexers parse backwards from the end of calldata and map the
// decoded ASCII code to a builder/app. The draft and tooling may evolve, so
// this parser is intentionally modular and conservative.
export const DEFAULT_ERC8021_SUFFIX_MARKER =
  "80218021802180218021802180218021";

const DEFAULT_MAX_BUILDER_CODE_BYTES = 96;
const DEFAULT_BUILDER_CODE_PATTERN =
  /^[A-Za-z0-9][A-Za-z0-9_.:-]{1,63}(,[A-Za-z0-9][A-Za-z0-9_.:-]{1,63})*$/;

function normalizeHex(input: string) {
  const value = input.trim();

  if (!value || value === "0x") {
    return null;
  }

  if (!/^0x[0-9a-fA-F]*$/.test(value) || value.length % 2 !== 0) {
    return null;
  }

  return value.slice(2).toLowerCase();
}

function normalizeMarker(marker: string) {
  const value = marker.trim().replace(/^0x/i, "").toLowerCase();

  if (!value || !/^[0-9a-f]+$/.test(value) || value.length % 2 !== 0) {
    return null;
  }

  return value;
}

function hexToAscii(hex: string) {
  let output = "";

  for (let index = 0; index < hex.length; index += 2) {
    const charCode = Number.parseInt(hex.slice(index, index + 2), 16);

    if (charCode < 32 || charCode > 126) {
      return null;
    }

    output += String.fromCharCode(charCode);
  }

  return output;
}

function firstBuilderCode(value: string) {
  return value
    .split(",")
    .map((code) => code.trim())
    .filter(Boolean)[0];
}

export function parseBuilderCodeFromCalldata(
  input: string,
  options: BuilderCodeParserOptions = {}
): BuilderCodeParseResult {
  try {
    const calldata = normalizeHex(input);

    if (!calldata) {
      return { found: false, reason: "Invalid or empty calldata." };
    }

    const marker = normalizeMarker(
      options.suffixMarker ?? DEFAULT_ERC8021_SUFFIX_MARKER
    );

    if (!marker) {
      return { found: false, reason: "Invalid suffix marker configuration." };
    }

    if (!calldata.endsWith(marker)) {
      return { found: false, reason: "ERC-8021 suffix marker not detected." };
    }

    const payloadBeforeMarker = calldata.slice(0, -marker.length);

    if (payloadBeforeMarker.length < 4) {
      return { found: false, reason: "ERC-8021 suffix is too short." };
    }

    const schemaId = payloadBeforeMarker.slice(-2);

    // MVP support is limited to schema 0, the known current Builder Codes
    // shape generated by Base/ox tooling. Additional schemas should be added
    // here instead of loosening detection.
    if (schemaId !== "00") {
      return { found: false, reason: "Unsupported ERC-8021 schema id." };
    }

    const beforeSchema = payloadBeforeMarker.slice(0, -2);
    const maxBuilderCodeBytes = Math.min(
      Math.max(options.maxBuilderCodeBytes ?? DEFAULT_MAX_BUILDER_CODE_BYTES, 1),
      255
    );
    const builderCodePattern =
      options.builderCodePattern ?? DEFAULT_BUILDER_CODE_PATTERN;

    for (let codeLength = maxBuilderCodeBytes; codeLength >= 1; codeLength -= 1) {
      const lengthByteStart = beforeSchema.length - codeLength * 2 - 2;

      if (lengthByteStart < 0) {
        continue;
      }

      const lengthByte = Number.parseInt(
        beforeSchema.slice(lengthByteStart, lengthByteStart + 2),
        16
      );

      if (lengthByte !== codeLength) {
        continue;
      }

      const builderCodeHex = beforeSchema.slice(
        lengthByteStart + 2,
        lengthByteStart + 2 + codeLength * 2
      );
      const decodedCodes = hexToAscii(builderCodeHex);

      if (!decodedCodes || !builderCodePattern.test(decodedCodes)) {
        continue;
      }

      return {
        found: true,
        builderCode: firstBuilderCode(decodedCodes),
        rawSuffix: `0x${beforeSchema.slice(lengthByteStart)}${schemaId}${marker}`,
        reason:
          decodedCodes.includes(",")
            ? "Multiple builder codes detected; using the first code."
            : "ERC-8021 Builder Code suffix detected."
      };
    }

    return {
      found: false,
      rawSuffix: `0x${payloadBeforeMarker.slice(-2)}${marker}`,
      reason: "ERC-8021 marker detected, but builder code payload was not recognized."
    };
  } catch {
    return { found: false, reason: "Unable to parse calldata safely." };
  }
}
